name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # تحديد نسخة مستقرة

      - name: Setup Project
        run: |
          flutter create --project-name smart_stock my_app
          rm my_app/lib/main.dart
          cp main.dart my_app/lib/main.dart

      - name: Build APK
        working-directory: my_app
        run: flutter build apk --debug --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartStock-App
          path: my_app/build/app/outputs/flutter-apk/app-debug.apk
