name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Preparation
        run: |
          flutter create --project-name smart_stock my_app
          # نقل الملف الذي رفعته يدوياً إلى مكانه الصحيح
          cp main.dart my_app/lib/main.dart
          cd my_app
          flutter build apk --debug --no-tree-shake-icons
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SmartStock-APK
          path: my_app/build/app/outputs/flutter-apk/app-debug.apk
